### PR TITLE
Create Cats

### PR DESCRIPTION
**Pull request by chrbknudsen**

### CODE REVIEW

**Comment by MariaJ89** [comment]
Good idea!

**Review by MariaJ89 — COMMENTED** [review]
Do you really think so...?

**Comment by chrbknudsen** [comment]
Kittens do. In a redwine sauce!

**Comment by MariaJ89** [comment]
Another theme for conservation or projects?

**Comment by chrbknudsen** [comment]
Nope. We have a catlover at the stage!

**Pull request merged**
